version = 1

test_patterns = [
  "test.go",
  "test/*.py",
  "test/*.go",
  "**/*_test.go"
]

exclude_patterns = [
  "examples/**",
  "travis/*.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "vitess.io/vitess"
  
[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "docker/base/Dockerfile",
    "docker/base/Dockerfile.mariadb",
    "docker/base/Dockerfile.mariadb103",
    "docker/base/Dockerfile.mysql56",
    "docker/base/Dockerfile.mysql80",
    "docker/base/Dockerfile.percona",
    "docker/base/Dockerfile.percona57",
    "docker/base/Dockerfile.percona80",
    "docker/bootstrap/Dockerfile.common",
    "docker/bootstrap/Dockerfile.mariadb",
    "docker/bootstrap/Dockerfile.mariadb103",
    "docker/bootstrap/Dockerfile.mysql56",
    "docker/bootstrap/Dockerfile.mysql57",
    "docker/bootstrap/Dockerfile.mysql57-arm64v8",
    "docker/bootstrap/Dockerfile.mysql80",
    "docker/bootstrap/Dockerfile.percona",
    "docker/bootstrap/Dockerfile.percona57",
    "docker/bootstrap/Dockerfile.percona80",
    "docker/lite/Dockerfile.mariadb",
    "docker/lite/Dockerfile.alpine",
    "docker/lite/Dockerfile",
    "docker/lite/Dockerfile.percona",
    "docker/lite/Dockerfile.mysql80",
    "docker/lite/Dockerfile.percona57",
    "docker/lite/Dockerfile.percona80",
    "docker/lite/Dockerfile.mysql57",
    "docker/lite/Dockerfile.mariadb103",
    "docker/lite/Dockerfile.mysql56",
    "docker/k8s/vtgate/Dockerfile",
    "docker/k8s/pmm-client/Dockerfile",
    "docker/k8s/vttablet/Dockerfile",
    "docker/k8s/mysqlctld/Dockerfile",
    "docker/k8s/Dockerfile",
    "docker/k8s/vtctld/Dockerfile",
    "docker/k8s/logrotate/Dockerfile",
    "docker/k8s/vtctl/Dockerfile",
    "docker/k8s/vtworker/Dockerfile",
    "docker/k8s/logtail/Dockerfile",
    "docker/k8s/vtbackup/Dockerfile",
    "docker/k8s/orchestrator/Dockerfile",
    "docker/k8s/vtexplain/Dockerfile",
    "docker/k8s/vtctlclient/Dockerfile",
    "docker/Dockerfile.release",
    "docker/root/Dockerfile",
    "docker/orchestrator/Dockerfile",
    "Dockerfile"
  ]
  
[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "2.x.x"
